import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { auth } from "@/auth";
import { signOut } from "@/auth";
import prisma from "@/lib/db";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  const username = session?.user?.email ? await prisma.user.findFirst({
    where: {
      email: session.user.email
    }
  }).then(x => x?.username) : null

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-[#f6f6ef]">
          <header className="bg-[#ff6600] p-2">
            <div className="container mx-auto flex items-center">
              <img
                alt="Y Combinator Logo"
                className="mr-2 h-5 w-5"
                height="20"
                src="/logo.png"
                style={{
                  aspectRatio: "20/20",
                  objectFit: "cover",
                }}
                width="20"
              />
              <nav className="flex space-x-4 text-sm font-semibold text-black">
                <Link className="hover:underline" href="/">
                  My HN
                </Link>
                <Link className="hover:underline" href="/newest">
                  new
                </Link>
                <Link className="hover:underline" href="/submit">
                  submit
                </Link>
              </nav>
              <div className="ml-auto">
                {session ? (
                  <>
                    <Link className="text-sm text-black hover:underline" href={`/user/${username!}`}>
                      {username!}
                    </Link>
                    <div className="text-sm text-black hover:underline" onClick={async () => {
                      "use server"
                      await signOut()
                    }}>
                      logout
                    </div>
                  </>
                ) : (
                  <Link className="text-sm text-black hover:underline" href="/login">
                    login
                  </Link>
                )}
              </div>
            </div>
          </header>
          <main className="container mx-auto py-4">
            {children}
          </main>
          <footer className="border-t border-gray-300 py-4 text-center text-xs text-gray-500">
            <nav className="space-x-4">
              <Link className="hover:underline" href="/newsguidelines">
                Guidelines
              </Link>
              <Link className="hover:underline" href="/newsfaq">
                FAQ
              </Link>
              <Link className="hover:underline" href="/api">
                API
              </Link>
              <Link className="hover:underline" href="/legal">
                Legal
              </Link>
              <Link className="hover:underline" href="/contact">
                Contact
              </Link>
            </nav>
          </footer>
        </div>
      </body>
    </html>
  );
}
